FROM postgres:15-alpine

# Копируем скрипт инициализации БД
COPY database/init.sql /docker-entrypoint-initdb.d/

# Установка прав
RUN chmod 644 /docker-entrypoint-initdb.d/init.sql

# Порт PostgreSQL
EXPOSE 5432